# Generated by Django 4.0.2 on 2022-02-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=256)),
                ('content_file', models.FileField(blank=True, default=None, null=True, upload_to='videos')),
                ('thumbnail_file', models.FileField(blank=True, default=None, null=True, upload_to='thumbnails')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('audio_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=256)),
                ('videos', models.ManyToManyField(blank=True, related_name='playlists', to='core.Video')),
            ],
        ),
    ]
