# Generated by Django 4.0.2 on 2022-02-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_playlist_downloaded_video_downloaded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="downloaded",
        ),
    ]
